# This is a basic workflow to help you get started with Actions

name: demo5

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     # - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: create a text file
        run: echo "Hello world" > hello.txt
        #upload artificat to create dependency to next next job
      - uses: actions/upload-artifact@v4
        with:
          name:hello-file
          path:hello.txt

  test:    
      runs-on: ubuntu-latest
      steps:
         #download artificat to create dependency to next next job
      - uses: actions/download-artifact@v4
        with:
          name:hello-file

      # Runs a set of commands using the runners shell
      - name: list file
        run: ls 
      - name: Test File
        run: cat hello.txt|grep -i "hello world"
      #    echo Add other actions to build,
       # echo test, and deploy your project.